branches: ['main']

plugins:
  - "@semantic-release/commit-analyzer"
  - - "@semantic-release/exec"
    - prepareCmd: "
        mkdir to_package &&
        cp Chart.yaml values.yaml index.yaml to_package &&
        cp -R templates to_package &&
        cd to_package &&
        sed -i -e 's/version: .*/version: ${nextRelease.version}/g' Chart.yaml &&
        cd .. && 
        mkdir -p dist &&
        helm package to_package --destination dist/ &&
        cd to_package &&
        rm index.yaml && helm repo index . &&
        cd .. &&
        rm -rf to_package
        "
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - ./to_package/index.yaml
        - ./to_package/Chart.yaml
      message: |
        chore(release): version ${nextRelease.version}
        \n
        \n
        ${nextRelease.notes}
  - - "@semantic-release/github"
    - assets:
        - path:
            - dist/*tgz
repositoryUrl: https://github.com/csye7125-fall2022-group01/helm-chart.git

# {

# "branches": ["main"],

#   "plugins": [
#     [
#       "semantic-release-helm3",
#       {
#         chartPath: './',
#         registry: 'https://github.com/csye7125-fall2022-group01/helm-chart'
#         # isChartMuseum: true
#       }
#     ]
#   ]
# }

# {
#     "branches": ["main",{ "name": "develop", "prerelease": true }],
#     "plugins": [
#       "@semantic-release/commit-analyzer",
#       "@semantic-release/release-notes-generator",
#       "@semantic-release/changelog",
#     [
#       "@semantic-release/npm",
#       {
#         "npmPublish": false
#      }
#     ],
#     ["@semantic-release/git", {
#       "assets": ["Chart.yml", "package.json"],
#       "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
#     }],
#     "@semantic-release/github"
#     ],
#   "repositoryUrl": "https://github.com/your_repository"

# }



        # tar -czvf dist/helm-${nextRelease.version}.tgz dist &&
