apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: webapp-hpa
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: {{ include "webapp.fullname" . }}-deploy
    minReplicas: 1
    maxReplicas: 5
    #metricsServer: https://dependency-metrics-server.metrics:443
    metrics:
    - type: Resource
    resource:
        name: cpu
        target:
        type: Utilization
        averageUtilization: 5